Vagrant.configure("2") do |config|

  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "geerlingguy/centos7"
    scriptbox.vm.network "public_network", bridge: "wlan0" # Replace "wlan0" with your actual network interface name
    scriptbox.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "geerlingguy/centos7"
    web01.vm.network "public_network", bridge: "wlan0" # Replace "wlan0" with your actual network interface name
  end
  
  config.vm.define "web02" do |web02|
    web02.vm.box = "geerlingguy/centos7"
    web02.vm.network "public_network", bridge: "wlan0" # Replace "wlan0" with your actual network interface name
  end

  config.vm.define "web03" do |web03|
    web03.vm.box = "ubuntu/bionic64"
    web03.vm.network "public_network", bridge: "wlan0" # Replace "wlan0" with your actual network interface name
  end
end

